### ISSUE TITLE
Install bug

### ISSUE THREAD

**Issue by wendyws** [maximsch2/pglasso#1]
Hi! I met a problem when installing pglasso package on python 2. The bug is as below. I have reinstalled the VCforpython27 but nothing worked. Could you please help me?
`error: command 'C:\\Users\\Wanyan Wendy Shao\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\link.exe' failed with exit status 1120`

**Comment by maximsch2** [comment]
Sorry, I'm not sure what is wrong with compiling binary extensions for Python on Windows in this particular case. Is there a longer error message? A few things that come to mind:
1) Try to see if Python you have is 64 bit version (as it looks like you are using 64 bit compiler).
2) Try new Ubuntu subsystem in Win10 and build it there using usual Linux compilers?

**Comment by wendyws** [comment]
Thank you for your reply! Currently, I'm trying to install pglasso on Linux subsystem. Below is more error information:
`'C:\Users\Wanyan Wendy Shao\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\link.exe /DLL /nologo /INCREMENTAL:NO "/LIBPATH:C:\Users\Wanyan Wendy Shao\Anaconda3\envs\py2\libs" "/LIBPATH:C:\Users \Wanyan Wendy Shao\Ananconda3\envs\py2\PCbuild\amd64" "/LIBPATH:C:\Users\Wanyan Wendy Shao\Anaconda3\envs\py2\PC\VS9.0\amd64" /EXPORT:init_pglasso build\temp.win-amd64-2.7\Release\_pglasso.obj /OUT:build\lib.win-amd64-2.7\_pglasso.pyd /IMPLIB:build\temp.win-amd64-2.7\Release\_pglasso.lib /MANIFESTFILE:build\temp.win-amd64-2.7\Release\_pglasso.pyd.manifest
_pglasso.obj : warning LNK4197: export 'init_pglasso' specified multiple times; using first specification
Creating library build\temp.win-amd64-2.7\Release\_pglasso.lib and object build\temp.win-amd64-2.7\Release\_pglasso.exp
_pglasso.obj : error LNK2019: unresolved external symbol fmin referenced in function __pyx_f_8_pglasso_new_py_dpglasso_shift
build\lib.win-amd64-2.7\_pglasso.pyd : fatal error LNK1120: 1 unresolved externals
error: command 'C:\\Users\\Wanyan Wendy Shao\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\link.exe' failed with exit status 1120`

**Comment by maximsch2** [comment]
Can you please try building from this branch to see if it works? https://github.com/maximsch2/pglasso/tree/proposed-fix

**Comment by wendyws** [comment]
Thank you for the update! I have tried to build on the above package. The problem that VC++ complier can't be linked with pglasso has  been solved. But there exists new problem while running the example.py posted on the http://pathglasso-leelab.cs.washington.edu/
When running `T = pglasso.pglasso(AML1_S, pathways, 0.15)`
The error info is as below
`Traceback (most recent call last):
  File "C:\Users\Wanyan Wendy Shao\Anaconda3\envs\py2\lib\site-packages\IPython\core\interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-17-914de614104b>", line 1, in <module>
    T = pglasso.pglasso(AML1_S, pathways, 0.15)
  File "_pglasso.pyx", line 904, in _pglasso.cpglasso_DC (_pglasso.c:21543)
  File "_pglasso.pyx", line 653, in _pglasso.setup_pathways (_pglasso.c:16822)
  File "_pglasso.pyx", line 140, in _pglasso.CSimplePathwayGeneral.__init__ (_pglasso.c:6850)
ValueError: Buffer dtype mismatch, expected 'long' but got 'long long'`
Meanwhile, I've tried to run the package(master branch) on the win10 ubuntu subsystem. Everything was fine except running `T = pglasso.pglasso(AML1_S, pathways, 0.15)`
The erro info is as below
`Traceback (most recent call last):
  File "/home/user/anaconda2/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2882, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-46-c7ed9a8dced8>", line 1, in <module>
    T = pglasso.pglasso(AML2_S, pathways, 0.15)
  File "_pglasso.pyx", line 902, in _pglasso.cpglasso_DC
  File "_pglasso.pyx", line 668, in _pglasso.get_pathway_graph
TypeError: add_edge() takes exactly 3 arguments (4 given)`
I think it's very strange as I've checked both lines in _pglasso.pyx which give the number of arguments exactly 3 not 4. 
The linux os version is Ubuntu 16.04.3, python version is python2.7.

**Comment by maximsch2** [comment]
Yeah, the first error seems to be another issue caused by compiling using VC, probably not worth it to try to ferret all of them out (although pull requests are welcome, of course).

The second one seems to be an issue with the version of the NetworkX package, can you see what version do you have installed? Downgrading it to 1.8 or 1.10 should do the trick, but I'll also look into the changes they made.
