### ISSUE TITLE
I meet a problem when I perform "python setup.py build"

### ISSUE THREAD

**Issue by xskyz** [maximsch2/pglasso#2]
error: command 'C:\\Users\\1\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\link.exe' failed with exit status 1120

I don't know how to solve it ,
and I want to know the execution environment of this code,
thank you for your help

**Comment by maximsch2** [comment]
We've resolved the issue through other channel
